name: Close All Existing PRs on New PR

on:
  pull_request:
    types: [opened, reopened] # This workflow triggers when a new pull request is opened or an existing one is reopened.
  workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions UI.

jobs:
  close_other_prs:
    runs-on: ubuntu-latest # The job will run on a fresh Ubuntu virtual machine.

    permissions:
      pull-requests: write # Grant write permission to the workflow for managing pull requests.

    steps:
      - name: Checkout repository # Checkout the repository code.
        uses: actions/checkout@v4

      - name: Get current PR number # Get the number of the pull request that triggered this workflow.
        # For workflow_dispatch, github.event.pull_request.number will be null, so we handle that.
        id: get_current_pr
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "CURRENT_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "CURRENT_PR_NUMBER=0" >> $GITHUB_OUTPUT # Use 0 or any placeholder for manual runs
          fi

      - name: List and Close Other Open Pull Requests # List all open PRs and close them, excluding the current one if triggered by a PR event.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the default GITHUB_TOKEN for authentication.
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Current PR event triggered: #${{ steps.get_current_pr.outputs.CURRENT_PR_NUMBER }}"
          else
            echo "Workflow manually triggered."
          fi
          echo "Listing all open pull requests..."

          # Get a list of all open pull request numbers as a JSON array
          OPEN_PR_NUMBERS=$(gh pr list --state open --json number | jq -r '.[].number')

          if [ -z "$OPEN_PR_NUMBERS" ]; then
            echo "No other open pull requests found to close."
          else
            echo "Found open PRs: $OPEN_PR_NUMBERS"
            for PR_NUMBER in $OPEN_PR_NUMBERS; do
              # If triggered by a pull_request event, skip the PR that triggered it.
              # For manual triggers, CURRENT_PR_NUMBER is 0, so this condition will always be true for valid PR numbers.
              if [ "$PR_NUMBER" -ne "${{ steps.get_current_pr.outputs.CURRENT_PR_NUMBER }}" ]; then
                echo "Closing pull request #${PR_NUMBER}..."
                if [ "${{ github.event_name }}" == "pull_request" ]; then
                  gh pr close "$PR_NUMBER" --comment "This pull request was automatically closed because a new pull request (#${{ steps.get_current_pr.outputs.CURRENT_PR_NUMBER }}) was opened or an existing one was reopened."
                else
                  gh pr close "$PR_NUMBER" --comment "This pull request was automatically closed by a manual workflow run."
                fi
                echo "Pull request #${PR_NUMBER} closed."
              else
                echo "Skipping the pull request #${PR_NUMBER} that triggered this workflow (if applicable)."
              fi
            done
          fi
